### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by sohini-roy** [sohini-roy/github-set-pr-status#6]
![screenshot from 2017-07-25 21-31-39](https://user-images.githubusercontent.com/16969415/28581739-b0d6471a-7180-11e7-8575-b37966dc5d48.png)
The first error is due to the asynchronous nature of JavaScript. The first "sohini-roy" is due to line:40 and the last one is from line:97. Clearly, 'data' definition executes itself before line:97.
The second error is from line:81. Have a look at authentication methods here: https://github.com/mikedeboer/node-github/blob/master/README.md

**Comment by sohini-roy** [comment]
could you have a look @gr2m . Thanks for helping.

**Comment by gr2m** [comment]
I `data` you pass [in line 114](https://github.com/sohini-roy/github-set-pr/blob/58c691d4ed7a419e9108d54c80f19edf2e75c009/index.js#L114) is an empty object as it is defined [in line 45](https://github.com/sohini-roy/github-set-pr/blob/58c691d4ed7a419e9108d54c80f19edf2e75c009/index.js#L45). 

You are sending 3 requests at once instead of one after the other. 

First, you can remove `github.authorization.create`, you already have a token as the user passes it in on the terminal, just remove the block. 

Next, you need to wait for the response from the PR to get the `sha` which we need to set the status. Move the `github.repos.createStatus` call into the `prResponse` function, that should do the trick.

Instead of sending a request with `request`, you can also you use the API that the `github` library gives you: [`github.pullRequests.get({ ... })`](http://mikedeboer.github.io/node-github/#api-pullRequests-get)

**Comment by sohini-roy** [comment]
Thanks for having a look. resolved in 1641687.
